baseURL = "https://utxos.org"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "utxos.org -- Bitcoin for Everyone"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-152627278-1"
disqusShortname = "utxos-org"
enableGitInfo = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "An extension to Bitcoin for unbounded payment capacity"
  homeMetaContent = "An extension to Bitcoin for unbounded payment capacity"
  footer = "Copyright Jeremy Rubin"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Implementations"
    url = "/Implementations/"
    weight = 5
  [[menu.nav]]
    name = "Alternatives"
    url = "/Alternatives/"
    weight = 6
  [[menu.nav]]
    name = "Impact Analysis"
    url = "/analysis/"
    weight = 4

  [[menu.nav]]
    name = "Use Cases"
    url = "/uses/"
    weight = 3
  [[menu.nav]]
    name = "BIP"
    url = "https://github.com/JeremyRubin/bips/blob/op-secure-the-bag/bip-secure-the-bag.mediawiki"
    weight = 2
