baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Secure The Bag"
theme = "cupper-hugo-theme"
googleAnalytics = "UA-123456789-1"
disqusShortname = "yourdiscussshortname"
enableGitInfo = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "An extension to Bitcoin for unbounded payment capacity"
  homeMetaContent = "An extension to Bitcoin for unbounded payment capacity"
  footer = "Copyright Jeremy Rubin"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Implementations"
    url = "/Implementations/"
    weight = 2
  [[menu.nav]]
    name = "Alternatives"
    url = "/Alternatives/"
    weight = 3
  [[menu.nav]]
    name = "Industrial Analysis"
    url = "/analysis/"
    weight = 3
