baseURL = "https://utxos.org"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "utxos.org -- Bitcoin for Everyone"
theme = "hugo-serif-theme"
disqusShortname = "utxos-org"
enableGitInfo = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99
[markup.goldmark.renderer]
  unsafe= true

[params]
  google_analytics_id = "UA-152627278-1"
  homeMetaContent = "An extension to Bitcoin for unbounded payment capacity"
  footer = "Copyright Jeremy Rubin"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = true
  [params.logo]
    mobile = "images/logo-mobile.svg"
    standard  = "images/logo.svg"
    alt = "utxos.org"

  [params.homepage_meta_tags]
    meta_description = "An extension to Bitcoin for unbounded payment capacity"
    meta_og_title = "utxos.org"
    meta_og_type = "website"
    meta_og_url = "https://utxos.org"
    meta_og_image = "https://utxos.org/static/images/og/main.png"
    meta_og_description = "utxos.org brings you the latest information about bitcoin payment scalability solutions."
    meta_twitter_card = "summary"
    meta_twitter_site = "@JeremyRubin"
    meta_twitter_creator = "@JeremyRubin"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
	identifier="bip"
    name = "BIP-119 Materials"
    weight = 2
      [[menu.main]]
        parent="bip"
        name = "Specification"
        url = "https://github.com/bitcoin/bips/blob/master/bip-0119.mediawiki"
        weight = 2
      [[menu.main]]
        parent="bip"
        name = "Deployment Options"
        url = "/deployment/"
        weight = 5
      [[menu.main]]
        parent="bip"
        name = "Alternative Designs"
        url = "/alternatives/"
        weight = 6
      [[menu.main]]
       parent="bip"
       name = "Workshops"
       url = "/workshops/"
       weight=7

  [[menu.main]]
	identifier="apps"
    name = "Applications"
    weight = 3
      [[menu.main]]
        parent="apps"
        name = "Use Cases"
        url = "/uses/"
        weight = 3
      [[menu.main]]
        parent="apps"
        name = "Ecosystem Impact"
        url = "/analysis/"
        weight = 4
      [[menu.main]]
        parent="apps"
        name = "Sapio"
        url = "https://learn.sapio-lang.org"
        weight = 5
  [[menu.main]]
    name="More Resources"
    url ="/resources/"
    weight=5

  [[menu.main]]
    name="Sponsors"
    url ="/sponsors/"
    weight=6
  [[menu.main]]
    name="Telegram"
    url ="https://t.me/op_ctv_chat"
